#!/usr/bin/env python3
"""Utility to read 'commits' file, display as a menu, and return numeric
   value of user's choice (0 being no-op)."""

import sys
from vyatta import get_cfg_version

# Main program
if __name__ == "__main__":
    sys.exit(get_cfg_version.get_config_version())
